### PR TITLE
feat: prevent core modules from getting loaded multiple times

### PR DESCRIPTION
**Pull request by sebawita**
This change should prevent `NativeScriptModule` and `NativeScriptAnimationsModule` from getting loaded in multiple `NgModules` across an Angular NativeScript app.

When the core modules are imported multiple times, this change will cause Errors to be thrown with the following message:

 * For NativeScriptModule:
 > NativeScriptModule has already been loaded. Import NativeScriptModule in the AppModule only.

 * For NativeScriptAnimationsModule:
> NativeScriptAnimationsModule has already been loaded. Import NativeScriptAnimationsModule in the AppModule only.

***BREAKING CHANGE:*** importing `NativeScriptModule` and `NativeScriptAnimationsModule` in multiple ngModules is no longer allowed.

To migrate:
 * in `AppModule`:
   * import `NativeScriptModule`
   * import`NativeScriptAnimationsModule` - only if you are planning to use Angular Animations
 * in the remaining modules:
   * remove `NativeScriptModule` imports and replace with `NativeScriptCommonModule` import
   * remove `NativeScriptAnimationsModule` imports

## Example
    
Before:
app.module.ts:
```
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { NativeScriptAnimationsModule } from 'nativescript-angular/animations';
...
@NgModule({
  imports: [
    NativeScriptModule,
    NativeScriptAnimationsModule
  ],
...
})
```

another.module.ts:
```
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { NativeScriptAnimationsModule } from 'nativescript-angular/animations';
...
@NgModule({
  imports: [
    NativeScriptModule,
    NativeScriptAnimationsModule
  ],
...
})
```
   
    
After:
app.module.ts:
```
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { NativeScriptAnimationsModule } from 'nativescript-angular/animations';
...
@NgModule({
  imports: [
    NativeScriptModule,
    NativeScriptAnimationsModule
  ],
...
})
```

another.module.ts:
```
import { NativeScriptCommonModule } from 'nativescript-angular/common';
...
@NgModule({
  imports: [
    NativeScriptCommonModule
  ],
...
})
```

### CODE REVIEW

**Comment by vchimev** [comment]
There are failing tests in the `e2e-renderer-android` suite:
```
should navigate to page.Action Bar scenario dynamically add/remove ActionItems should navigate to page
should find elements.Action Bar scenario dynamically add/remove ActionItems should find elements
should initially render the action items in the correct order.Action Bar scenario dynamically add/remove ActionItems should initially render the action items in the correct order
should detach first element when its condition is false.Action Bar scenario dynamically add/remove ActionItems should detach first element when its condition is false
should attach first element in the correct position.Action Bar scenario dynamically add/remove ActionItems should attach first element in the correct position
should detach second element when its condition is false.Action Bar scenario dynamically add/remove ActionItems should detach second element when its condition is false
should attach second element in the correct position.Action Bar scenario dynamically add/remove ActionItems should attach second element in the correct position
should detach and then reattach both at correct places.Action Bar scenario dynamically add/remove ActionItems should detach and then reattach both at correct places
```

**Comment by vchimev** [comment]
There is a failing test in the `e2e-router-ios` suite:
```
should navigate to lazy/home.Navigate to lazy module should navigate to lazy/home
```

**Comment by sebawita** [comment]
I've made the requested changes

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
branch_sdk

**Comment by sis0k0** [comment]
test branch_sdk

**Comment by sis0k0** [comment]
test branch_sdk

**Comment by sis0k0** [comment]
test

**Pull request merged**
