### PR TITLE
fix(animations): use parsers from core modules

### LINKED ISSUE #738: Transform animation parser fails with eg. transform: 'scale(2,2)'
I posted about this accidentally to nativescript main issue board; since I have zeroed in on the root cause of why certain animations cause the element to disappear.

Here's the original issue I posted with isolated component example for verifying the issue and all other details:
https://github.com/NativeScript/NativeScript/issues/3937

In the comments you can see what I found out to be the cause.

### PR DESCRIPTION
**Pull request by sis0k0**
fixes #738

### CODE REVIEW

**Comment by sis0k0** [comment]
run ci

**Comment by sis0k0** [comment]
run ci

**Comment by sis0k0** [comment]
uitests android

**Comment by sis0k0** [comment]
run ci

**Comment by vchimev** [comment]
sdkwebpack

**Comment by sis0k0** [comment]
run ci

**Pull request merged**
