### PR TITLE
fix: page navigation bug if there's not outlet for frame after cleari…

### PR DESCRIPTION
**Pull request by bellalMohamed**
Fix for #2232

### CODE REVIEW

**Comment by bellalMohamed** [comment]
@cla-bot check

**Comment by NathanWalker** [comment]
Thank you @bellalMohamed !! we'll publish a patch out with this on thursday ❤️

**Comment by NathanWalker** [comment]
@bellalMohamed published in `10.0.3` now, thanks again.

**Comment by Motyldrogi** [comment]
@NathanWalker I need the excact same fix for **@angular/nativescript**.
I upgraded to Angular 10 and changed to **@angular/nativescript**, now i have the same problem as before this fix.
I tried to transfer the fix to **@angular/nativescript** but somehow it's a whole other structure and i don't know how.

**Pull request merged**
