### PR TITLE
chore: bump Angular versions to 5.2.0

### PR DESCRIPTION
**Pull request by sis0k0**

### CODE REVIEW

**Comment by SvetoslavTsenov** [comment]
sdkwebpack

**Comment by SvetoslavTsenov** [comment]
testsappngwebpack

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by jogboms** [comment]
@sisOkO i'm still wondering what means to add certain `angularCompilerOption`s to our projects.
Should we use the object passed into `NativeScriptAngularCompilerPlugin` within `webpack.config.js`?

**Pull request merged**
