### PR TITLE
fix: revert recursive remove -causing crashes

### PR DESCRIPTION
**Pull request by vakrilov**
This reverting the recursive removeChild implemented in #1740 by @m-abs 
We found the following issues and decided to revert the change until they are resolved:
1. #1818 - Error: `Cannot read property 'textTransform' of undefined` in `createSpannableStringBuilder`
2. Crash in [nativescript-sdk-examples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng) with tab view. To reproduce go to : `TabView` -> `Basic` -> `[back]`. You get a crash (in console) and cannot navigate any more

### CODE REVIEW

**Comment by SvetoslavTsenov** [comment]
test sdk_ng

**Comment by SvetoslavTsenov** [comment]
test sdk_ng

**Comment by m-abs** [comment]
I think, i know what causes this.

I removed the test for Span and FormattedString, thinking isDetachedView would handle it.

**Comment by vakrilov** [comment]
I have fixed `1.`  in https://github.com/NativeScript/NativeScript/pull/7237
However, the issue with the TabView seems more tricky. That's why we decided to revert for now.

**Pull request merged**
