### PR TITLE
feat: NS 4.0 Integration

### PR DESCRIPTION
**Pull request by vakrilov**
**TODO:** Nice description of changes

### CODE REVIEW

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Pull request merged**
