### PR TITLE
Add tests to ensure native setters are called exactly once

### PR DESCRIPTION
**Pull request by PanayotCankov**
when components are instantiated

Depends on https://github.com/NativeScript/NativeScript/pull/4227
Before that commit native setters for background in iOS are called about 12 times.

### CODE REVIEW

**Comment by vakrilov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
@PanayotCankov, can you try to rebase again

**Comment by vchimev** [comment]
Currently, the publishing of `tns-core-modules@next` fails. The PR tests will past after a new version of `tns-core-modules` is uploaded.

**Comment by sis0k0** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
router-android
router-ios

**Comment by vchimev** [comment]
router-android

**Comment by vchimev** [comment]
router-ios

**Comment by vchimev** [comment]
router-android

**Comment by vchimev** [comment]
router-android

**Comment by vchimev** [comment]
router-android

**Comment by vchimev** [comment]
router-android

**Comment by vchimev** [comment]
router-android

**Comment by vchimev** [comment]
router-android

**Pull request merged**
