### PR TITLE
fix(NativeScriptPlatformRef): Destroy lastModuleRef on exitEvent

### LINKED ISSUE #923: ngOnDestroy not called on Android back button
We ran into an issue with ngOnDestroy not being called when we use the Android back button.

I've provided a sample application:
https://github.com/dennis-montana/back-button-issue

If you run the app on Android and click the back button you can see that ngOnDestroy isn't called while the native activityDestroyedEvent from Android is being called.
The app is still running in a sleeping state so everything created in ngOnInit is being created again every time a user uses the back button.

If you run the demo app you can see the following output:
```
### Opened the app 1st time
JS: AppComponent ngOnInit

### Clicked back button
JS: Android activity destroyed

### Opened the app 2nd time
JS: handleResumeEvent
JS: AppComponent ngOnInit

### Clicked back button
JS: Android activity destroyed
JS: Android activity destroyed

### Opened the app 3rd time
JS: handleResumeEvent
JS: handleResumeEvent
JS: AppComponent ngOnInit

### Clicked back button
JS: Android activity destroyed
JS: Android activity destroyed
JS: Android activity destroyed
```
As you can see the calls are being stacked.

### PR DESCRIPTION
**Pull request by m-abs**
- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-angular/blob/master/DevelopmentWorkflow.md#running-the-tests
- ~Tests for the changes are included.~ **Don't see how**

## What is the current behavior?

The application module isn't destroyed when the application exitEvent is triggered.
This causes the previous instance of the nativescript-angular app to be running in a sleep state and `ngOnDestroy()` on it's compoments, services etc. are not called as expected.

## What is the new behavior?
Adds an event listener for the `exitEvent` in the `NativeScriptPlatformRef` which destroys the `lastModuleRef` which triggers `ngOnDestroy()` as expected.

Fixes #923

### CODE REVIEW

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
LGTM!
Also I think this is more of a `fix` than a chore so I have renamed the PR title.

**Comment by vakrilov** [comment]
test

**Comment by etabakov** [comment]
@cla-bot check

**Comment by m-abs** [comment]
Hi @vakrilov,

I just noticed a problem
 
On Android 9.
1. Launch an app with this patch applied.
2. Go to system settings -> Accessibility -> Font size and change the font size.
3. Go back to the app.

This will have triggered an exit event and tried to destroy the angular application, but it is still running.
Now in a broken state.

You can see the problem here:
1. Checkout https://github.com/m-abs/tns-ng-leak
2. npm install && bash ./patches/apply-patches.sh
3. Follow the steps above.

I print out the app events:
```bash
JS: suspend << Leave the app to change the font size
JS: activityPaused
JS: activityStopped
JS: orientationChanged << Font size changed in while I'm in settings
JS: exit << Returned to the app
JS: activityDestroyed
JS: activityCreated
JS: activityStarted
JS: activityResumed
JS: resume
JS: displayed
JS: displayed
```

**Comment by m-abs** [comment]
I solved the problem.

The `exit` event is triggered because the `MainActivity.onDestroy()` is called as a part of a restart needed to apply the new settings.

I added a test for this case in the `exit` event handler.

**Comment by elena-p** [comment]
test

**Comment by elena-p** [comment]
run ci

**Comment by elena-p** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Pull request merged**
