### PR TITLE
refactor(router): Implement page navigation with RouteReuseStrategy (#949)

### PR DESCRIPTION
**Pull request by vakrilov**
Use `RouteReuseStrategy` implementation to do page navigation with `<page-router-outlet>`

### CODE REVIEW

**Comment by sis0k0** [comment]
uitests

**Comment by sis0k0** [comment]
uitests

**Comment by sis0k0** [comment]
uitests

**Comment by jogboms** [comment]
Thanks @vakrilov. This fixed the `clearHistory` issue. 👍

**Comment by jogboms** [comment]
```
JS: ERROR Error: Uncaught (in promise): Error: Currently not in page back navigation - component should be detached instead of deactivated.
JS: Error: Currently not in page back navigation - component should be detached instead of deactivated.
JS:     at PageRouterOutlet.deactivate (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:134:19) [angular]
JS:     at ActivateRoutes.deactivateRouteAndOutlet (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/@angular/router/bundles/router.umd.js:4544:32) [angular]
JS:     at ActivateRoutes.deactivateRouteAndItsChildren (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/@angular/router/bundles/router.umd.js:4514:18) [angular]
JS:     at ActivateRoutes.deactivateRoutes (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/@angular/router/bundles/router.umd.js:4500:22) [angular]
JS:     at file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/@angular/router/bundles/router.umd.js:4466:19 [angular]
JS:     at Array.forEach (native) [angular]
JS:     at ActivateRoutes.deactivateChildRoutes (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/@angular/router/bundles/router.umd.js:4464:29) [angular]
JS:     at ActivateRoutes.activate (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/@angular/router/bundles/router.umd.js:4450:14) [angular]
JS:     at file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/@angular/router/bundles/router.umd.js:4064:22 [angular]
JS:     at SafeSubscriber._next (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/rxjs/Observable.js:224:21) [angular]
JS:     at SafeSubscriber.__tryOrSetError (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/rxjs/Subscriber.js:247:16) [angular]
JS:     at SafeSubscriber.next (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/rxjs/Subscriber.js:187:27) [angular]
JS:     at Subscriber._next (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/rxjs/Subscriber.js:125:26) [angular]
JS:     at Subscriber.next (file:///data/data/com.rfnl.fixershubclient/files/app/tns_modules/rxjs/Subscriber.js:89:18) [angular]
```

Any particular reason why i would be getting this for a forward navigation?

```
    "@angular/router": "^4.2.6",
    "nativescript-angular": "^4.3.0-2017-9-7-3",
    "tns-core-modules": "^3.2.0",
```

**Comment by vakrilov** [comment]
There is a problem with the new routing-strategy when using lazy-modules. We will be looking into this in a next few days. Hopefully there will be another patch soon.

**Comment by jogboms** [comment]
Thanks. Would be looking forward to this.

**Pull request merged**
