### PR TITLE
fix(forms): Changed the TextValueAccessor to apply ng-touched on blur

### PR DESCRIPTION
**Pull request by vultix**
## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [X] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] You have signed the [CLA](http://www.nativescript.org/cla).
- [X] All existing tests are passing: https://github.com/NativeScript/nativescript-angular/blob/master/DevelopmentWorkflow.md#running-the-tests
- [ ] Tests for the changes are included.

## What is the current behavior?
The moment a TextField or TextView is touched the onTouched() function is called on the valueAccessor.  This changes the ng-untouched class to ng-touched. See [#1063](https://github.com/NativeScript/nativescript-angular/issues/1063) and [Playground Demo](https://play.nativescript.org/?template=play-ng&id=fXyTwz)

## What is the new behavior?
The TextValueAccessor now waits for the blur event before marking the field as touched.

This is the angular-core behavior as can be seen [here](https://stackblitz.com/edit/angular-bnaeqr?file=app%2Fapp.component.html).

Fixes [#1063](https://github.com/NativeScript/nativescript-angular/issues/1063), [#804](https://github.com/NativeScript/nativescript-angular/issues/804).

### CODE REVIEW

**Comment by gms1** [comment]
this PR would fix  "TextField having wrong value if updateOn: 'blur'" :+1: 

https://github.com/angular/angular/blob/master/packages/forms/src/directives/control_value_accessor.ts
On **blur**, your class should call the registered function to allow
the forms API to update itself

**Comment by manoldonev** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Comment by manoldonev** [comment]
test

**Pull request merged**
