### PR TITLE
fix(router): fix return value for getTransition of NSRouterLink

### LINKED ISSUE #1784: Default transition of Frame is not used when using NsRouterLink
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.1
 - Cross-platform modules: 5.3.1
 - Android Runtime: 5.3.1
 - iOS Runtime: 5.3.1
 - NativeScript-Angular: 5.3.1
 - Angular: 7.2.9
 
**Describe the bug**
When setting the static `defaultTransition` property on the `Frame` class, the transition is not used, when navigation is initiated by tapping on an nsRouterLink that does not specify any transition using the `[transition]` input.

**To Reproduce**
Set `Frame.defaultTransition` to any valid `NavigationTransition` object. Tap on a button that has a `nsRouterLink` directive with no explicitly set transition. The default transition is not applied to this navigation.

**Expected behavior**
The default transition specified by setting `Frame.defaultTransition` should be used when there is no explicitly set transition on an nsRouterLink.

**Additional context**
This is due to NsRouterLink returning an empty object for the transition in the `getTransition` method (https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/ns-router-link.ts#L117) when no transition is explicitly set. In this case, the transition input defaults to `true`, which leads the `getTransition` method to return an empty object for the `transition` property. As the Frame checks whether the transition property is `undefined` to decide whether to use the default transition, this leads to the default transition not being used.

### PR DESCRIPTION
**Pull request by flore2003**
Return undefined transition value from getTransition method of NSRouterLink when boolean value is used for pageTransition input. Fixes #1784

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-angular/blob/master/DevelopmentWorkflow.md#running-the-tests
- [x] Tests for the changes are included.

## What is the current behavior?
The `getTransition` method of `NSRouterLink` returns an empty object value for the transition property, when the ´pageTransition´ input is given a boolean value. This leads to the defaultTransition of the Frame not being applied.

## What is the new behavior?
The `getTransition` method of `NSRouterLink` now returns undefined as the value for the transition property.

Fixes #1784.

### CODE REVIEW

**Comment by VladimirAmiorkov** [comment]
test

**Comment by flore2003** [comment]
Any news on this PR?

**Comment by VladimirAmiorkov** [comment]
Hi @flore2003 ,

The PR has been reviewed but is not yet merged because we are in the process of a release which is planned for later this week. After that release we will update this PR to the latest branch and process it. Sorry for the delay caused by our current release plan.

**Comment by VladimirAmiorkov** [comment]
test

**Pull request merged**
