### PR TITLE
feat: Angular 6.0 rc initial support

### PR DESCRIPTION
**Pull request by sis0k0**
- Bumps the dependency versions;
- migrates rxjs6 imports;
- disables strict metadata emit until https://github.com/angular/angular/issues/23310 is resolved.

Should be merged with rebase and merge.

### CODE REVIEW

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test webpack#sis0k0/webpack4

**Comment by SvetoslavTsenov** [comment]
test branch_webpack#sis0k0/webpack4

**Comment by sis0k0** [comment]
test branch_webpack#sis0k0/webpack4

**Comment by SvetoslavTsenov** [comment]
test branch_teststappng#ng6 branch_groceriess#ng6

**Comment by SvetoslavTsenov** [comment]
test branch_teststappng#sis0k0/ng6 branch_groceriess#sis0k0/ng6

**Comment by SvetoslavTsenov** [comment]
test branch_ testsappng#sis0k0/ng6 branch_ groceries#sis0k0/ng6

**Comment by SvetoslavTsenov** [comment]
test branch_ testsappng#sis0k0/ng6 branch_ groceries#sis0k0/ng6 branch_webpack#sis0k0/webpack4

**Comment by sis0k0** [comment]
test branch_ testsappng#sis0k0/ng6 branch_ groceries#sis0k0/ng6 branch_webpack#sis0k0/webpack4

**Comment by SvetoslavTsenov** [comment]
test branch_testsappng#sis0k0/ng6 branch_groceries#sis0k0/ng6 branch_webpack#sis0k0/webpack4

**Comment by SvetoslavTsenov** [comment]
test branch#sis0k0/ng6 branch_webpack#sis0k0/webpack4

**Comment by SvetoslavTsenov** [comment]
test branch_webpack#sis0k0/webpack4 branch#sis0k0/ng6

**Comment by manoldonev** [comment]
test branch_webpack#sis0k0/webpack4 branch#sis0k0/ng6

**Comment by SvetoslavTsenov** [comment]
test branch_webpack#sis0k0/webpack4 branch#sis0k0/ng6

**Comment by sis0k0** [comment]
test

**Pull request merged**
