### PR TITLE
feat: Support custom ErrorHandlers

### PR DESCRIPTION
**Pull request by m-abs**
implements #951 

With this PR projects can create their own ErrorHandler and inject it in their `AppModule`, NativeScriptModule will now use that ErrorHandler over its own.

I've added a new test in ng-sample, switch to `ErrorHandlerAppComponent` in the app.ts to test the ErrorHandler.

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
run uitests

**Comment by SvetoslavTsenov** [comment]
run ci

**Comment by vakrilov** [comment]
Hey @m-abs,
We finally had some times to review this PR (sorry, it took us ages to do so).
I'm wondering why did you propose the changes in the `nativescript-angular/nativescript.module.ts`. I tried to register a custom `ErrorHandler` with the current official version and it worked as expected. [Here is a ns-playgorund app with the experiment](https://play.nativescript.org/?id=fEpRbaJXLw0d1U6o7XaAw&template=play-ng)

One thing it is worth noting (because it hit me when I was doing the sample) - you should only import `NativeScriptModule` in your **root module** and import `NativeScriptCommonModule` inside the feature modules. Using `NativeScriptModule` in a feature module may lead to a new default `ErrorHandler` being created.

**Comment by m-abs** [comment]
@vakrilov 
It's been so long since I made it, os it's hard to remember exactly.
I know we had problems getting the errors from angular, and it was solved with my patch.
But I just tried without it and it works as expected...

I'm closing the PR as it is clearly not needed.

**Comment by Bolhy10** [comment]
Que hiciste para resolver el ErrorHandler, estoy probando y no me captura mu handler personalizado

**Pull request closed without merging**
