### PR TITLE
Standardize templated items component

### PR DESCRIPTION
**Pull request by PeterStaev**
Implements #1222

### CODE REVIEW

**Comment by PeterStaev** [comment]
So 6+ months after the submission this is still not merged w/o any further comments... So much for "We love PRs"...

**Comment by NathanWalker** [comment]
I was looking at this recently and also wondering why something so helpful was just sitting here. Thanks for your effort Peter.

**Comment by shiv19** [comment]
This definitely deserves some love for sure. Can't believe it hasn't been merged yet.

**Comment by shiv19** [comment]
@vakrilov any reason for delaying review of this PR?

**Comment by vakrilov** [comment]
Hey @PeterStaev 
First of all, apologies for the total lack of feedback about this PR (and the feature) form our side. We have discussed internally a number of times and it is clear that it is clever approach and useful code. 

The reason that we didn't merge it right away is that there were some ideas to even further extend this PR with some of the functionality in the [RadListView](https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/overview). We never did carry out these ideas though :(

I can see clearly, that we communicated this one poorly - so apologies again. Here is a plan to action:

1. I will work on bringing this PR up to date this week
2. We'll merge it in `master` as long as all is ListView tests green
3. We think about extending and improving with `RadListView` features after

Frankly, this should have been the plan from the begging and I'm glad you brought this PR into view again 🙏🙏🙏

**Comment by vakrilov** [comment]
Closing in favor of #1520
Thanks @PeterStaev !

**Pull request closed without merging**
