### PR TITLE
feat(Http): can optionally fetch local resources from app bundle with Http

### PR DESCRIPTION
**Pull request by NathanWalker**
This provides a nice convenience for Angular developers; an easy way to fetch local files with `Http` from their app bundle just like they would local files in their web app using the same semantics as NativeScript XML `Image` src property.

```
this.http.get(`~/assets/data.json`)
      .map((response: Response) => response.json())
      .subscribe((results: string[]) => {
        // we have results!
      });
```
... is now possible 👍

### CODE REVIEW

**Comment by NathanWalker** [comment]
This now has tests with helpful mocks :+1:

**Comment by NathanWalker** [comment]
TODO:

- [ ] Conditionally provide `Http` whether user is using `HTTP_PROVIDERS` or not

**Comment by NathanWalker** [comment]
As far as any debate around ‘is it right to allow Http module to request local files’… the main question is does `Http` allow local files to be requested from a web server, and the answer is ​*Yes*​. That’s how web devs see it… If a file is in their web app and it can be requested via XMLHttpRequest, which it can, the same expectation will be brought to their approach to {N}… they will want to be able to intutively request files from their app with Http… just my 2 cents…. this was one of those things when I started with `nativescript-angular`, I just expected to work and didn’t understand why it didnt… since i am a hardened web dev.

Outside of those logical reasons… it is just convenient sugar… and devs love sugar… it’s what makes for a happier dev experience imo.

**Comment by NathanWalker** [comment]
This PR also fixes the new error occuring for some folks with latest that's in 0.1.8 and the new router:
```
ORIGINAL EXCEPTION: Error: not implemented
ORIGINAL STACKTRACE:
Error: not implemented
    at NativeScriptDomAdapter.Parse5DomAdapter.getCookie (/data/data/org.nativescript.nativescriptweather/files/app/tns_modules/@angular/platform-server/src/parse5_adapter.js:612:68)
```

**Comment by vakrilov** [comment]
👍

**Comment by hdeshev** [comment]
:+1:

**Pull request merged**
