### PR TITLE
feat: add Angular 9 and Ivy support

### PR DESCRIPTION
**Pull request by VladimirAmiorkov**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-angular/blob/master/DevelopmentWorkflow.md#running-the-tests
- [ ] Tests for the changes are included.

## What is the current behavior?
Current package does not work with Angular 9.0.0-rc.1 version.

## What is the new behavior?
Current package does works with Angular 9.0.0-rc.1 version.

Fixes/Implements/Closes #[Issue Number].
Resolves https://github.com/NativeScript/nativescript-angular/issues/2060

### CODE REVIEW

**Comment by VladimirAmiorkov** [comment]
test

**Comment by MattRiddell** [comment]
Any idea when this will be merged?

**Comment by NathanWalker** [comment]
I took over from where @VladimirAmiorkov left off and got things working with Ivy enabled here:
https://github.com/NativeScript/nativescript-angular/pull/2124

So everyone here does not need to wait until that new PR is merged, you can do the following to try the new v9 by doing the following:

1. Download a prepacked `@nativescript/angular` v9 here:
https://drive.google.com/file/d/1MyKOetI5aLc7gA_M3rKrNS-1RqztOwDs/view?usp=sharing

Unzip and put in root of your {N} project.

2. Download a prepacked `nativescript-angular` compatibility reference here (this is mainly to allow other plugins which may not use the new @nativescript scope to still work):
https://drive.google.com/file/d/1xQ7O66qE2hmTbeChL1nbFqh4rCEEaor0/view?usp=sharing

Unzip and put in root of your {N} project.

3. Then modify you package.json as follows:

* Add to your `scripts` section:

```
"scripts": {
  "ngcc": "ngcc",
  "postinstall": "ngcc"
}
```

* Modify `dependencies` as follows:

```
"@nativescript/angular": "file:nativescript-angular-v9.tgz",
"nativescript-angular": "file:nativescript-angular-compat.tgz",
```

Then just make sure all your `@angular` dep's are updated to `~9.0.0`, for example:
`"@angular/core": "~9.0.1"`

Also make you are using at least 1.4.0 or 1.5.0 of `nativescript-dev-webpack` in devDependencies.

4. Modify your `tsconfig.json` to include this (parallel to `compilerOptions`):

```
"compilerOptions": {
  ...your various options, etc.
},
"angularCompilerOptions": {
    "enableIvy": true
}
```

Then clean you project completely:
```
rm -rf node_modules/ platforms/ package-lock.json hooks
```

Then run with the following:
```
tns run ios --emulator --env.aot --no-hmr
```

Best to always use AoT all the time since Ivy works with it by default and also good to disable hmr as seems there's some other things to get hmr working with ivy.

**Comment by thegnuu** [comment]
Is there an estimated date when this will be available?

We are using [`immer`](https://github.com/immerjs/immer) in our application and we need typescript 3.7 that we are able to create our next release ;)

I know that I am able to patch this version into our project, but I am not really under pressure to create a new release and if it takes just a few weeks to publish this I would like to wait for the release...

If it will take months I am happy to follow the instructions to patch it!

Thank you for your help!

**Comment by mavaanan** [comment]
We would also need this support ASAP. Can you give some time estimate for Angular 9.0.2+ support?

**Comment by abcfoundry** [comment]
Is this progressing?  Releases used to be aligned with Angular, has something changed in the relationship with working with the google team?

**Comment by VladimirAmiorkov** [comment]
With deep sadness I must inform you that I am no longer working on the NativeScript project. It has been a great journey and my work on the Angular 9 Ivy implementation in NativeScript has been taken over in the this PR https://github.com/NativeScript/nativescript-angular/pull/2124 . Please follow it and contribute to it as you can.

**Pull request closed without merging**
