### PR TITLE
fix(tabview): implemented setter for TabViewItem's config

### LINKED ISSUE #845: TabView *tabItem binding not updating value
Test application to demonstrate the issue [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/test/tabViewSelectedIndex)

E.g.
```
<TabView #tv iosIconRenderingMode="alwaysTemplate" (selectedIndexChange)="onIndexChange($event)" selectedTabTextColor="green">
    <StackLayout *tabItem="myFirstItem">
        <Label text="First tap" textWrap="true"></Label>
    </StackLayout>
    <StackLayout *tabItem="mySecondItem">
        <Label text="Second tab item"></Label>
    </StackLayout>
    <StackLayout *tabItem="myThirdItem">
        <Label text="Third tab item"></Label>
    </StackLayout>
</TabView>
```

where **myFirstItem** is tabItem object of the follwing kind
```
this.myFirstItem = { title: "Selected", iconSource: "~/images/logo.png" };
```

Result: [Changing the value via binding](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/test/tabViewSelectedIndex/app/item/items.component.ts#L22-L51) won't be respected

### PR DESCRIPTION
**Pull request by Buuhuu**
I implemented a setter for the configuration so that the binding can change the configuration and apply the changes to the underlying view. I kept all of the previous getters/setters decorated as inputs even tough they are not working as expected. This is for compatibility reasons and can be challenged. The implementation of each has been adapted to use the new configuration setter to apply the configuration change.

Fixes #845

### CODE REVIEW

**Comment by MartoYankov** [comment]
test

**Comment by MartoYankov** [comment]
test

**Comment by MartoYankov** [comment]
test

**Comment by MartoYankov** [comment]
test

**Comment by MartoYankov** [comment]
test

**Comment by Buuhuu** [comment]
Thank you.

**Pull request merged**
