### PR TITLE
Added SegmentedBarItem to element registry.

### PR DESCRIPTION
**Pull request by nsndeck**
Added SegmentedBarItem to element registry. And now `SegmentedBarItem` could be added via HTML.

```HTML
<SegmentedBar>
    <SegmentedBarItem title="Waiting" ></SegmentedBarItem>
    <SegmentedBarItem title="Done" ></SegmentedBarItem>
</SegmentedBar>
```

### CODE REVIEW

**Comment by dbenninger** [comment]
This works on iOS, but on Android I get the following error:

Unhandled Promise rejection: Error in pages/rides/rides.html:2:8 caused by: Cannot read property 'newTabSpec' of undefined ; Zone: angular ; Task: Promise.then ; Value: Error: Error in pages/rides/rides.html:2:8 caused by: Cannot read property 'newTabSpec' of undefined TypeError: Cannot read property 'newTabSpec' of undefined
JS:     at SegmentedBar.insertTab (/data/data/net.comerge.PubliBikeLocal/files/app/tns_modules/ui/segmented-bar/segmented-bar.js:153:31)
JS:     at SegmentedBar._addChildFromBuilder (/data/data/net.comerge.PubliBikeLocal/files/app/tns_modules/ui/segmented-bar/segmented-bar-common.js:113:18)
JS:     at ViewUtil.insertChild (/data/data/net.comerge.PubliBikeLocal/files/app/tns_modules/nativescript-angular/view-util.js:59:20)
JS:     at ViewUtil.createAndAttach (/data/data/net.comerge.PubliBikeLocal/files/app/tns_modules/nativescript-angular/view-util.js:103:18)
JS:     at ViewUtil.createView (/data/data/net.comerge.PubliBikeLocal/files/app/tns_modules/nativescript-angular/view-util.js:110:25)
JS:     at NativeScriptRenderer.createElement (/data/data/net.comerge.PubliBikeLocal/files/app/tns_modules/nativescript-angular/renderer.js:198:30)
JS:     at DebugAppView._View_RidesComponent0.createInternal (RidesComponent.ngfactory.js:31:30)
JS:     at DebugAppView.AppView.create (/data/data/net.comerge.PubliBikeLocal/files/app/tns_modules/@angular/core/bundles/core.umd.js:9419:25)
JS:     at DebugAppView.create (/data/data/net.comerge.PubliBikeLocal/files/app/tns_modules/@angular/core/bundles/core.umd.js:9631:48)
JS:     at DebugAppView._View_RidesComponent_Host0.createInternal (RidesComponent_Host.ngfactory.js:18:14)
JS: Error: Uncaught (in promise): Error: Error in pages/rides/rides.html:2:8 caused by: Cannot read property 'newTabSpec' of undefined

**Comment by adisoftbn** [comment]
I get the same error on android, sadly...

**Comment by playmuser** [comment]
Same error...

**Comment by rhanbIT** [comment]
Same error..

**Comment by murphmar** [comment]
Having this issue as well. This is almost a year old, any update here at all?

**Comment by OscarLopezArnaiz** [comment]
I managed to fix it by adding a setTimeOut into the 'insertTab' prototype method. It seems android bridge to native is not there on time, (quite heavy stuff to be exported, I guess). No need to add time to the setTimeOut though, moving it to the bottom of the stack is enough. 
screen shot 2017-03-13 at 10 55 38

**Comment by murphmar** [comment]
That worked for me, awesome! 

Only now I have another issue. The segmented bar items repeat to the end of the view until I do something to refresh the view. Ie: I have Daily, Weekly, Monthly SegmentedBarItems and it displays "Daily/Weekly/Monthly/Daily/Weekly/Monthly" until I navigate to another page, when I go back it displays them correctly. Hmm.

**Comment by OscarLopezArnaiz** [comment]
Yep, went throughout it too @murphmar . Managed to fix it by not using <SegmentedBar.items> element.

Try this
SegmentedBar>
    <SegmentedBarItem title="Daily" />
    <SegmentedBarItem title="Weekly" />
    <SegmentedBarItem title="Monthly" />
</SegmentedBar>

Let me know how that goes.

Thanks

**Comment by murphmar** [comment]
@OscarLopezArnaiz Still the same issue for me. What ended up working for me was creating the whole thing programmatically on the component.

**Pull request merged**
