### PR TITLE
docs: fix link

### PR DESCRIPTION
**Pull request by radeva**

### CODE REVIEW

**Comment by sis0k0** [comment]
test

**Comment by sis0k0** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules#latest

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules#latest

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules#latest

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules#latest

**Comment by SvetoslavTsenov** [comment]
test tns-core-modules#latest android#latest

**Pull request merged**
