### PR TITLE
Support Angular RC5

### PR DESCRIPTION
**Pull request by hdeshev**
## The Mother of All Pull Requests!

- Migrate to Angular 2 RC5.
- Bootstrapping apps now done with NgModule's. The old `nativescriptBootstrap` method is gone, and apps should switch to the `platformNativeScriptDynamic().bootstrapModule(MyAppModule)` API. Yes, **ALL CLIENT APPS NEED TO BE CHANGED**
- The library entrypoint is now the `nativescript-angular/platform` module. Import `NativeScriptRouterModule` from `nativescript-angular/router` and `NativeScriptFormsModule` from `nativescript-angular/forms` respectively if you want to use routing and form value accessor directives.
- Remove all traces of `router-deprecated`.

## Known Issues
- Karma test runner almost always hangs on Travis (yes, again!)
- `tests/app/tests/snippets.ts` test never raises router `NavigationStart` event.

Ping @nsndeck, @vakrilov

### CODE REVIEW

**Comment by hdeshev** [comment]
I published the package to npm as version `0.4.0-beta1` under the `angular2-rc5`, so people could try it out easily :)

**Comment by nsndeck** [comment]
:+1:

**Comment by vakrilov** [comment]
👍

**Comment by mko** [comment]
Any idea when this will be integrated?

**Comment by NathanWalker** [comment]
@hdeshev I was able to use the `0.4.0-beta1` tag to update https://github.com/NathanWalker/angular2-seed-advanced to rc.5 and it works great.
Thank you for that 👍

**Pull request merged**
