### PR TITLE
feat: update to Angular 5 animations and add support for AnimationBuilder

### PR DESCRIPTION
**Pull request by sis0k0**
depends on: https://github.com/NativeScript/NativeScript/pull/5134
Example on using AnimationBuilder (you'll have to use this branch of ns-ng to make it work): https://github.com/NativeScript/ns-ng-animation-examples/blob/master/app/animation-builder.component.ts

related to #1073

### CODE REVIEW

**Comment by sis0k0** [comment]
run ci

**Comment by sis0k0** [comment]
e2e

**Comment by sis0k0** [comment]
e2e

**Comment by sis0k0** [comment]
run ci

**Comment by sis0k0** [comment]
run ci

**Comment by SvetoslavTsenov** [comment]
webpack-testsappng

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by SvetoslavTsenov** [comment]
testsappng

**Comment by SvetoslavTsenov** [comment]
sdkwebpack

**Pull request merged**
