### PR TITLE
Add iOS 13 to dev-appium tests

### PR DESCRIPTION
**Pull request by DimitarTodorov**

### CODE REVIEW

**Comment by elena-p** [comment]
test nativescript-dev-webpack@latest

**Comment by DimitarTodorov** [comment]
test nativescript-dev-webpack#latest

**Comment by DimitarTodorov** [comment]
test nativescript-dev-webpack#latest tns-core-modules#latest

**Comment by DimitarTodorov** [comment]
cla-bot check

**Comment by DimitarTodorov** [comment]
@cla-bot check

**Comment by DimitarTodorov** [comment]
test nativescript-dev-webpack#latest tns-core-modules#latest

**Comment by DimitarTodorov** [comment]
test nativescript-dev-webpack#latest tns-core-modules#latest

**Comment by DimitarTodorov** [comment]
test nativescript-dev-webpack#latest tns-core-modules#latest

**Pull request merged**
