### PR TITLE
fix(modal): missing animated & stretched params

### LINKED ISSUE #1292: [ModalService] no animated or stretched params (NS4.0)
It seems to me that ModalService is lacking the `animated` and `stretched` params introduced in TNS 4.0. See https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view/view.d.ts#L529

Would be nice to have access to these from angular so we can disable animations or replace it with our own etc.

### PR DESCRIPTION
**Pull request by ddfreiling**
## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [X] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] You have signed the [CLA](http://www.nativescript.org/cla).
- [X] All existing tests are passing: https://github.com/NativeScript/nativescript-angular/blob/master/DevelopmentWorkflow.md#running-the-tests
- [X] Tests for the changes are included.

## What is the current behavior?
ModalDialogOptions did not include the new `animated` and `stretched` params introduced with Nativescript 4.0

## What is the new behavior?
ModalDialogOptions now includes optional `animated` and `stretched` params

Fixes #1292

No breaking changes, no migration steps.

## Question for reviewer

In dialogs.ts parentView is typed as ViewBase, but in my experience was always a View at runtime, is it safe to cast this instead of checking instanceof?

### CODE REVIEW

**Comment by manoldonev** [comment]
@ddfreiling I don't think it was our intention to provide a different API for View/ViewBase.showModal(...) so I streamlined it with https://github.com/NativeScript/NativeScript/pull/5734.

Also, generally there are scenarios where we would like to open a modal view from ViewBase instance (e.g. TabViewItem) but it seems this functionality was not working at the moment -- made a second PR to fix it: https://github.com/NativeScript/NativeScript/pull/5737

Till both PRs are merged and released I would suggest you to replace the snippet
```
// parentView typed as ViewBase, but only View takes stretched param.
if (parentView instanceof View) {
    parentView.showModal(page, context, closeCallback, fullscreen, animated, stretched);
} else {
    parentView.showModal(page, context, closeCallback, fullscreen, animated);
}
```

with
```
// TODO: remove <any> cast after https://github.com/NativeScript/NativeScript/pull/5734 is merged
(<any>parentView).showModal(page, context, closeCallback, fullscreen, animated, stretched);
```

**Comment by ddfreiling** [comment]
@manoldonev updated to new showModal signature

**Comment by manoldonev** [comment]
@ddfreiling can you use the \<any> cast above as thou the PRs are merged they are not public yet (no tns-core-modules official releases):
``` ts
// TODO: remove <any> cast after https://github.com/NativeScript/NativeScript/pull/5734 is merged
(<any>parentView).showModal(page, context, closeCallback, fullscreen, animated, stretched);
```

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Comment by manoldonev** [comment]
test

**Pull request merged**
