### PR TITLE
revert(router): page navigation with RouteReuseStrategy

### PR DESCRIPTION
**Pull request by sis0k0**
Due to problems with lazy loaded routes.

### CODE REVIEW

**Comment by sis0k0** [comment]
uitests

**Comment by NathanWalker** [comment]
Hi @sis0k0 I'm curious if this fixes this issue on latest at moment when navigating to pages at times:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'reusedRoute' of undefined
JS: TypeError: Cannot read property 'reusedRoute' of undefined
JS:     at PageRouterOutlet.activateOnGoBack (file:///data/data/com.ugroupmedia.pnp.client.mobile/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:270:18)
JS:     at PageRouterOutlet.activateWith (file:///data/data/com.ugroupmedia.pnp.client.mobile/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:217:18)
JS:     at ActivateRoutes.activateRoutes (file:///data/data/com.ugroupmedia.pnp.client.mobile/files/app/tns_modules/@angular/router/bundles/router.umd.js:4764:40)
```
If so, curious if any reasonable estimate on a merge to master? Just curious :)

**Comment by vakrilov** [comment]
Hi @NathanWalker 
This is just a revert of the changes form last week related to the router. They don't work when there is lazy loading involved, so we decided to revert the changes until we have a more stable implementation.

That said, I'm not sure which exactly is the issue you mentioned - is it logged?

**Comment by sis0k0** [comment]
uitests

**Pull request merged**
