### PR TITLE
Activate TestBed for NativeScript Angular Apps

### PR DESCRIPTION
**Pull request by hypery2k**
This adds support for jasmine/mocha angular testing using the TestBed class exported by Angular.

Fixes: #752, #479, #606

- [x] Zone.js loads appropriate patches for jasmine/mocha
- [x] Existing tests switched to TestBed from TestApp
- [x] TestBed specs passing

Updated Version of #1061 

Also this needs to be resolved: #https://github.com/NativeScript/zone.js/pull/1

### CODE REVIEW

**Comment by justindujardin** [comment]
Are you kidding me? Please close this blatant hijacking of my hard work.

**Comment by hypery2k** [comment]
sorry, got we wrong. Just wanted to rebased. Doesn't want to overtake your work

**Comment by hypery2k** [comment]
sorry

**Comment by justindujardin** [comment]
Arg, yeah no problem. I'm sensitive because that took a lot of work. I rebased the PR branch for you. 👍

**Comment by hypery2k** [comment]
I was a the train and just tried your changes. Don't want to got the earnings for your work. I really pleased your work. Would be great to have TestBed in NativeScript. I currently try to speed up the nativescript-angular ci build.

But for now, merry christmas

**Comment by justindujardin** [comment]
Hey, thanks for the kind words. :)

I have spoken with @vakrilov about TestBed at length, he's also excited, so I'm sure it will get merged sometime after the new year.

I hope you enjoy your holidays and such.

**Comment by hypery2k** [comment]
Thanks, wish you also great holidays and let’s make NativeScript better ;)

**Pull request closed without merging**
