### PR TITLE
fix(renderer): stop performing value conversions

### LINKED ISSUE #799: A binding does not work properly
The [item-detail](https://github.com/NativeScript/template-hello-world-ng/blob/master/item/item-detail.component.html#L4) component of the default hello world [template](https://github.com/NativeScript/template-hello-world-ng/) does not render properly. In particular:
```
<Label class="h2" [text]="item.id + '. '"></Label>
```

Expected:
*10. Messi*
screen shot 2017-05-15 at 9 16 29 am

Actual:
*10Messi*
screen shot 2017-05-15 at 9 04 11 am

### PR DESCRIPTION
**Pull request by sis0k0**
These conversions are now handled by core modules. The conversions
performed in the renderer and value accessors are no longer needed.

fixes #799

### CODE REVIEW

**Comment by sis0k0** [comment]
run uitests android

**Comment by sis0k0** [comment]
run testsappng

**Comment by sis0k0** [comment]
run uitests android

**Comment by SvetoslavTsenov** [comment]
run testsappng

**Comment by SvetoslavTsenov** [comment]
run testsappng

**Comment by sis0k0** [comment]
run testsappng

**Comment by sis0k0** [comment]
run ci

**Comment by sis0k0** [comment]
run uitests android

**Pull request merged**
