### PR TITLE
Fix navigate with clearHistory to a lazy loaded module

### PR DESCRIPTION
**Pull request by lfabreges**
Fix the navigation using extras like `clearHistory` to a lazy loaded module. Providers, especially `NSLocationStrategy` were instantiated multiple times.

### CODE REVIEW

**Comment by patrickpereira** [comment]
Can't wait to have PR! Great job!

Any tips on how to use this PR without having to wait for the repo to be updated?

**Comment by lfabreges** [comment]
I've duplicate the module in my app and use it as follows

```ts
import { NgModule, ModuleWithProviders, NO_ERRORS_SCHEMA } from "@angular/core";
import { RouterModule, Routes, ExtraOptions } from "@angular/router";
import { LocationStrategy, PlatformLocation } from "@angular/common";
import { NSRouterLink } from "nativescript-angular/router/ns-router-link";
import { NSRouterLinkActive } from "nativescript-angular/router/ns-router-link-active";
import { PageRouterOutlet } from "nativescript-angular/router/page-router-outlet";
import { NSLocationStrategy, LocationState } from "nativescript-angular/router/ns-location-strategy";
import { NativescriptPlatformLocation } from "nativescript-angular/router/ns-platform-location";
import { RouterExtensions } from "nativescript-angular/router/router-extensions";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";

export { PageRoute } from "nativescript-angular/router/page-router-outlet";
export { RouterExtensions } from "nativescript-angular/router/router-extensions";
export { NSModuleFactoryLoader } from "nativescript-angular/router/ns-module-factory-loader";
export type LocationState = LocationState;

@NgModule({
    declarations: [
        NSRouterLink,
        NSRouterLinkActive,
        PageRouterOutlet
    ],
    imports: [
        RouterModule,
        NativeScriptModule
    ],
    exports: [
        RouterModule,
        NSRouterLink,
        NSRouterLinkActive,
        PageRouterOutlet
    ],
    schemas: [NO_ERRORS_SCHEMA]
})
export class CustomRouterModule {
    static forRoot(routes: Routes, config?: ExtraOptions): ModuleWithProviders {
        return {
            ngModule: CustomRouterModule,
            providers: [
                NSLocationStrategy,
                { provide: LocationStrategy, useExisting: NSLocationStrategy },
                NativescriptPlatformLocation,
                { provide: PlatformLocation, useClass: NativescriptPlatformLocation },
                RouterExtensions,
                ...RouterModule.forRoot(routes, config).providers
            ]
        };
    }

    static forChild(routes: Routes): ModuleWithProviders {
        return {
            ngModule: CustomRouterModule,
            providers: RouterModule.forChild(routes).providers
        };
    }
}
```

**Comment by hdeshev** [comment]
This looks great, but unfortunately it breaks AoT compilation for me:

```sh
~/t/test-router $ ./node_modules/.bin/ngc -p tsconfig.aot.json 
Can't resolve all parameters for provideLocationStrategy in /home/local/TELERIK/hdeshev/tmp/test-router/node_modules/@angular/router/src/router_module.d.ts: ([object Object], ?, [object Object]).
```

The error goes away if I try the master branch. Any ideas?

**Comment by lfabreges** [comment]
It seems that the compiler is unable to resolve the @Inject(APP_BASE_HREF) parameter,. According to this thread https://github.com/angular/angular/issues/8623, `deps` should't use the `new Inject()` format but instead directly reference the token. I don't know why they still do it that way in the RouterModule.

It causes the compiler to flag the dependency with `hasUnknowDeps` in the `_getDependenciesMetadata` function of `compiler/src/metadata_resolver.ts`. `paramEntry` is just an object since not decorated and thus not recognized by the `instanceof Inject`.

**Comment by lfabreges** [comment]
I've find another way, will do PR tomorrow if travis is OK

**Comment by tskweres** [comment]
I'm golden, let's get it in!

**Comment by danielgek** [comment]
@hdeshev will this get merged in time for 2.5 release?

**Comment by hdeshev** [comment]
Thanks, great work! I tested it with @tskweres's project from #643. Too bad about the router module improvements. :(

@lfabreges, can you squash your commits and I'll try to get them in the upcoming release.

**Comment by hdeshev** [comment]
@danielgek Yes, that's the plan. I hope I can move it to the release branch tomorrow.

**Comment by tskweres** [comment]
#643 with respect to this bug, I'm still seeing the transitions issue. I clone my example repo, update core modules and re-add platform ios and build. 

Any thoughts on if 2.5 included the fix? Or am I missing a step?

**Comment by tskweres** [comment]
got it working with tns update next

**Pull request merged**
