### PR TITLE
feat(router): enable flexible page router outlets

### PR DESCRIPTION
**Pull request by MartoYankov**
- Enable multiple named page-router-outlets at root level.
 - Handle back navigation with multiple named outlets.
 - Enable navigation inside modal view.

### CODE REVIEW

**Comment by MartoYankov** [comment]
test

**Comment by MartoYankov** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Comment by MartoYankov** [comment]
test

**Comment by MartoYankov** [comment]
test branch_testsappng#ns-40

**Comment by MartoYankov** [comment]
test branch_testsappng#ns-40

**Comment by SvetoslavTsenov** [comment]
TestsAppNg is not building for both platforms. Probably not 

ERROR in node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
app/list-view/async-pipe-template.component.ts(1,10): error TS2305: Module '"/Users/nsbuilduser/workspace/composite-testsappng/tests-app-ng/node_modules/rxjs/Observable"' has no exported member 'Observable'.
app/list-view/multiple-templates.component.ts(1,10): error TS2305: Module '"/Users/nsbuilduser/workspace/composite-testsappng/tests-app-ng/node_modules/rxjs/Observable"' has no exported member 'Observable'.
app/button/button-text-alignment.component.ts(1,10): error TS2305: Module '"/Users/nsbuilduser/workspace/composite-testsappng/tests-app-ng/node_modules/rxjs/Observable"' has no exported member 'Observable'.

**Comment by sis0k0** [comment]
@SvetoslavTsenov @MartoYankov  The [`ns-40`](https://github.com/NativeScript/tests-app-ng/tree/ns-40) branch in [`nativescript/tests-app-ng`](https://github.com/NativeScript/tests-app-ng) is not compatible with NG 6. It should be rebased on top of the `master` branch.

**Comment by MartoYankov** [comment]
test branch_testsappng#ns-40

**Pull request merged**
