### PR TITLE
fix(modal): throw from core properly caught and rejected

### PR DESCRIPTION
**Pull request by NathanWalker**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-angular/blob/master/DevelopmentWorkflow.md#running-the-tests
- [ ] Tests for the changes are included.

## What is the current behavior?

App crashes if modal handling is invalid.

## What is the new behavior?

Developers can now properly handle such a crash in the promise rejection of the `ModalDialogService`'s `showModal` handling.

### CODE REVIEW

**Comment by NathanWalker** [comment]
This or https://github.com/NativeScript/NativeScript/pull/5841 are viable fixes to this problem.
Both would probably be the most bullet proof but I'd be happy with just this one at a minimum.

**Comment by dtopuzov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Comment by vakrilov** [comment]
test

**Pull request merged**
